// Package plugin is the pages plugin: the smallest complete example of a
// plugin that puts web content into Gridwell. It projects nothing — no
// directory, no process table, no API. Every page it serves is generated by
// gridwell-plugins/pages/site, so the plugin is only the wire half: keys in,
// bytes out.
//
// The whole point is ServeContent. A listed entry that declares serves_page
// is a page tile, and descending into one asks this plugin for HTML through
// the node's content door; a resource the page names by a relative URL comes
// back as the same call with a subpath. The plugin never learns the tile's
// id, the page's address, or where it is on a grid: those are node facts.
package plugin

import (
	"context"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	"github.com/josephburnett/gridwell-plugins/pages/site"
	pluginv1 "github.com/josephburnett/gridwell/api/gen/plugin/v1"
	"github.com/josephburnett/gridwell/api/rpc"
)

// Kind is the plugin's declared kind, and the suffix of its binary name.
const Kind = "pages"

// displayName is the plugin's own name for itself: the fallback when
// server.yaml configures no label.
const displayName = "pages"

// Plugin implements pluginv1.PluginServer over the sample site. It has no
// fields: the site is fixed, the plugin holds no node fact, and there is
// nothing to configure.
type Plugin struct {
	pluginv1.UnimplementedPluginServer
}

// FromConfig builds the plugin from the spawn config, and is the one
// config-to-plugin derivation. This plugin takes no config keys of its own,
// so it ignores what it is handed rather than refusing it: the node always
// passes uuid, kind and state_dir, and a plugin that refused an unknown key
// would refuse every launch.
func FromConfig(map[string]string) (pluginv1.PluginServer, error) {
	return New(), nil
}

// New builds the plugin.
func New() *Plugin { return &Plugin{} }

func (p *Plugin) Info(context.Context, *pluginv1.InfoRequest) (*pluginv1.InfoResponse, error) {
	return &pluginv1.InfoResponse{
		Kind:        Kind,
		DisplayName: displayName,
		// The one collection this plugin serves: the site. It declares no
		// label, so the swatch reads as the configured instance.
		MenuEntries: []*pluginv1.MenuEntry{{Id: site.RootContext, Context: site.RootContext}},
		// host_content stays false, unlike fs and proc: this plugin's grid is
		// not a window onto state that lives outside Gridwell. The pages are
		// the plugin's own content, so the tiles wear the ordinary treatment.
		HostContent: false,
	}, nil
}

// List enumerates the site. It is authoritative — the site is fixed, so a key
// absent from this listing is gone rather than unseen — and every context
// other than the root answers an empty listing, because there is only one.
func (p *Plugin) List(_ context.Context, req *pluginv1.ListRequest) (*pluginv1.ListResponse, error) {
	resp := &pluginv1.ListResponse{Authoritative: true, SourceLabel: displayName}
	if req.Context != site.RootContext {
		return resp, nil
	}
	for _, d := range site.Docs() {
		e := &pluginv1.Entry{
			Key:   d.Key,
			Label: d.Label,
			// Kind is "text" for every entry, page or not. serves_page is a
			// separate declaration on the same text row: it says the entry
			// has web bytes to serve, not that it is a url. A url entry owns
			// an address of its own, which is the opposite of what a page
			// tile is — the node derives a page's address when the page is
			// opened, so the plugin has none to declare.
			Kind: rpc.KindText,
			// Every doc's ReadContent body is markdown, so every entry
			// declares the same presentation. One rule, no per-doc switch.
			TextPresentation: rpc.TextPresentationBoth,
			ServesPage:       d.Page != nil,
			PlacementHint:    &pluginv1.PlacementHint{X: d.Col, Y: d.Row, W: 2, H: 2},
		}
		if d.Page != nil {
			// The face is the plugin's thumbnail. The site never changes, so
			// there is one generation of it forever.
			e.PreviewStamp = site.PreviewStamp
		}
		resp.Entries = append(resp.Entries, e)
	}
	return resp, nil
}

// ReadContent answers a doc's markdown body: what the tile reads as a
// document, for a page tile as much as a text one. An unknown key is an empty
// chunk, not an error — absence is Probe's answer to give.
func (p *Plugin) ReadContent(req *pluginv1.ReadContentRequest, stream pluginv1.Plugin_ReadContentServer) error {
	d := site.Lookup(req.Key)
	if d == nil {
		return stream.Send(&pluginv1.ContentChunk{})
	}
	return stream.Send(&pluginv1.ContentChunk{
		Data:      []byte(d.Note),
		MediaType: "text/markdown",
	})
}

// ServeContent is the web door's plugin half. Subpath "" is the doc's page;
// any other subpath is one of that page's own resources, named by the page's
// relative URLs and resolved by the browser against the tile's address. A
// subpath the page does not name is a 404 page rather than an error: the door
// is a browser's, and a missing resource is an ordinary web answer.
func (p *Plugin) ServeContent(req *pluginv1.ServeContentRequest, stream pluginv1.Plugin_ServeContentServer) error {
	d := site.Lookup(req.Key)
	if d == nil || d.Page == nil {
		return notFound(stream)
	}
	if req.Subpath == "" {
		return stream.Send(&pluginv1.ServeContentChunk{
			Status:    200,
			MediaType: "text/html; charset=utf-8",
			Data:      d.HTML(),
		})
	}
	asset, ok := d.Page.Assets[req.Subpath]
	if !ok {
		return notFound(stream)
	}
	return stream.Send(&pluginv1.ServeContentChunk{
		Status:    200,
		MediaType: asset.MediaType,
		Data:      asset.Data,
	})
}

// notFound is the door's own 404: a real HTTP status on the first chunk, so
// the node writes 404 headers and the browser sees a miss rather than a
// gateway failure.
func notFound(stream pluginv1.Plugin_ServeContentServer) error {
	return stream.Send(&pluginv1.ServeContentChunk{
		Status:    404,
		MediaType: "text/plain; charset=utf-8",
		Data:      []byte("not found"),
	})
}

// GetPreview answers a page tile's face. A doc with no page has no thumbnail,
// and nil is that answer — never an error.
func (p *Plugin) GetPreview(_ context.Context, req *pluginv1.GetPreviewRequest) (*pluginv1.GetPreviewResponse, error) {
	d := site.Lookup(req.Key)
	if d == nil {
		return &pluginv1.GetPreviewResponse{}, nil
	}
	return &pluginv1.GetPreviewResponse{Jpeg: d.PreviewJPEG()}, nil
}

// Probe answers definitively either way: the site is a fixed list, so a key
// it does not hold is gone, not merely unreadable this pass.
func (p *Plugin) Probe(_ context.Context, req *pluginv1.ProbeRequest) (*pluginv1.ProbeResponse, error) {
	if site.Lookup(req.Key) == nil {
		return &pluginv1.ProbeResponse{Presence: pluginv1.ProbeResponse_PRESENCE_GONE}, nil
	}
	return &pluginv1.ProbeResponse{Presence: pluginv1.ProbeResponse_PRESENCE_PRESENT}, nil
}

// Delete is refused rather than left to the embedded Unimplemented, so the
// reason travels: the sample site is fixed, and a delete that silently did
// nothing would look to the user like a delete that failed to stick.
func (p *Plugin) Delete(context.Context, *pluginv1.DeleteRequest) (*pluginv1.DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "pages plugin: the sample site is fixed; nothing to delete")
}
